/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/chair.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Chair = (props) => {
  const { nodes, materials } = useGLTF('./models/chair.glb');
  const leatherTextureProps = useTexture({
    // map: "./textures/leather/Leather_008_Base Color.jpg",
    normalMap: './textures/leather/Leather_008_Normal.jpg',
    roughnessMap: './textures/leather/Leather_008_Roughness.jpg',
    aoMap: './textures/leather/Leather_008_Ambient Occlusion.jpg'
  });
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.PTRCUY86TZ2AT30P001.geometry}
        // material={materials.ASSET_MAT_MR}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.03}
      >
        <meshStandardMaterial {...leatherTextureProps} />
      </mesh>
    </group>
  );
};

useGLTF.preload('./models/chair.glb');

export default Chair;
