/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/chair.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { Text } from '@react-three/drei'; // Import Text component từ @react-three/drei
import { useCustomization } from '../../contexts/Customization';
const GamingChair = (props) => {
  const { nodes, materials } = useGLTF('./models/chair.glb');
  const { threadColor, chairColor, cushionColor, textField } =
    useCustomization();

  return (
    <group {...props} dispose={null} scale={2.5}>
      <mesh
        geometry={nodes.thread.geometry}
        material={materials['outline.002']}
        position={[-0.006, 0.774, -0.178]}
        rotation={[1.605, 0, 0]}
        scale={[0.132, 0.143, 0.096]}
        onBeforeRender={() => {
          materials['outline.002'].color.set(threadColor.color); // Đặt màu đỏ
        }}
      />
      <mesh
        geometry={nodes.cushion.geometry}
        material={materials['Material.001']}
        position={[-0.008, 0.571, -0.129]}
        rotation={[-0.208, 0, 0]}
        scale={[0.119, 0.115, 0.093]}
        onBeforeRender={() => {
          materials['Material.001'].color.set(cushionColor.color);
        }}
      />

      <mesh
        geometry={nodes.body.geometry}
        material={materials['black_skin.006']}
        position={[-0.006, 0.774, -0.178]}
        rotation={[1.605, 0, 0]}
        scale={[0.132, 0.143, 0.096]}
        onBeforeRender={() => {
          materials['black_skin.006'].color.set(chairColor.color);
        }}
      />
      <Text
        position={[-0.006, 1.02, -0.2]}
        fontSize={0.05} // Kích thước chữ
        color="white" // Màu chữ
        anchorX="center" // Căn giữa chữ
        anchorY="middle" // Căn giữa chữ
        font="/fonts/Oswald-VariableFont_wght.ttf"
      >
        {textField} {/* Nội dung văn bản */}
      </Text>
      <group
        position={[0.214, 0.018, 0.206]}
        rotation={[-Math.PI / 2, 0, -0.73]}
        scale={-0.283}
      >
        <mesh
          geometry={nodes.Object_19002.geometry}
          material={materials['black_plactic.002']}
        />
        <mesh
          geometry={nodes.Object_19002_1.geometry}
          material={materials['black_skin.009']}
        />
        <mesh
          geometry={nodes.Object_19002_2.geometry}
          material={materials['metal.002']}
        />
        <mesh
          geometry={nodes.Object_19002_3.geometry}
          material={materials['Material.002']}
        />
      </group>
    </group>
  );
};

useGLTF.preload('./models/chair.glb');

export default GamingChair;
