/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/sofa.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { useCustomization } from '../../contexts/Customization';

const Sofa = (props) => {
  const { nodes, materials } = useGLTF('./models/sofa.glb');
  const { chairColor, cushionColor } = useCustomization();

  return (
    <group {...props} dispose={null} scale={3}>
      <mesh
        geometry={nodes.Plane045.geometry}
        material={materials.Wood}
        position={[0.648, 0.245, 0.237]}
        rotation={[0, -0.346, 0]}
        scale={0.01}
        onBeforeRender={() => {
          materials.Wood.color.set(chairColor.color); // Đặt màu đỏ
        }}
      />
      <group
        position={[-0.73, 0.016, 0.203]}
        rotation={[Math.PI / 2, 0, 3.139]}
        scale={0.01}
      >
        <mesh geometry={nodes.Mesh017.geometry} material={materials.Gold} />
        <mesh
          geometry={nodes.Mesh017_1.geometry}
          material={materials['Material #25']}
        />
        <mesh geometry={nodes.Mesh017_2.geometry} material={materials.Wood} />
        <mesh
          geometry={nodes.Mesh017_3.geometry}
          material={materials['Material #30ds']}
        />
      </group>
      <mesh
        geometry={nodes.Plane055.geometry}
        material={materials['Material #25']}
        position={[0.599, 0.491, 0.55]}
        rotation={[1.585, -0.04, 1.036]}
        scale={0.01}
        onBeforeRender={() => {
          materials['Material #25'].color.set(cushionColor.color); // Đặt màu đỏ
        }}
      />
    </group>
  );
};

useGLTF.preload('./models/sofa.glb');
export default Sofa;
